# -*- coding: utf-8 -*-
"""HW3_Q2_SohamSarkar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4-T8liZMrApVBJoOc_lzZseIaUPRQ2j
"""

!pip install pyspark

from google.colab import files
uploaded = files.upload()

import os
os.listdir('.')

import csv
from pyspark import SparkContext
import os

# Initialize Spark Context
sc = SparkContext.getOrCreate()
# Helper Function for Data Cleaning
def parse_temp_csv(line):
    # Use csv module to handle potential quotes and commas within fields
    reader = csv.reader([line])
    columns = next(reader)
    # Filter out header or malformed lines
    if not columns or columns[0] == "Region":
        return None
    try:
        # Columns: Region(0), Country(1), State(2), City(3), Month(4), Day(5), Year(6), AvgTemperature(7)
        region = columns[0]
        country = columns[1]
        city = columns[3]
        year = columns[6]
        temp = float(columns[7])

        # Most temperature datasets use -99 or -99.9 for missing data
        if temp <= -90:
            return None
        return (region, country, city, year, temp)
    except:
        return None
# Load the temperature dataset
temp_raw = sc.textFile("city_temperature(1).csv")
# Apply cleaning and filter out None values
temp_data = temp_raw.map(parse_temp_csv).filter(lambda x: x is not None).cache()

# Part A: Min/Max Temperature per Region
# Map to (Region, (Temp, Temp)) where the tuple is (min_candidate, max_candidate)
region_min_max = temp_data.map(lambda x: (x[0], (x[4], x[4]))) \
                          .reduceByKey(lambda a, b: (min(a[0], b[0]), max(a[1], b[1])))
print(" Part A: Min and Max Temp per Region")
for region, (min_t, max_t) in region_min_max.collect():
    print(f"{region}: Min={min_t}, Max={max_t}")
# Part B: Avg Temp by Year for "Europe"
# Filter for Europe, map to (Year, (Temp, 1)) to calculate sum and count
europe_avg = temp_data.filter(lambda x: x[0] == "Europe") \
                     .map(lambda x: (x[3], (x[4], 1))) \
                     .reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1])) \
                     .mapValues(lambda x: x[0] / x[1]) \
                     .sortByKey()
print("\n Part B: Avg Temp in Europe by Year")
print(europe_avg.collect())

# Part C: Top 10 Cities in "United States"
# Filter for US, map to (City, (Temp, 1)), then calculate average
us_top_cities = temp_data.filter(lambda x: x[1] == "US") \
                         .map(lambda x: (x[2], (x[4], 1))) \
                         .reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1])) \
                         .mapValues(lambda x: x[0] / x[1]) \
                         .takeOrdered(10, key=lambda x: -x[1])
print("\n Part C: Top 10 Warmest US Cities")
for city, avg_temp in us_top_cities:
    print(f"{city}: {avg_temp:.2f}")

# Helper: Function to save results
def save_rdd(rdd, folder_name):
    import os
    if os.path.exists(folder_name):
        os.system(f"rm -rf {folder_name}")
    rdd.saveAsTextFile(folder_name)
# Part D: Capital City Avg Temp by Year
# Parse the country-list file
def parse_country_list(line):
    reader = csv.reader([line])
    cols = next(reader)
    if not cols or cols[0] == "country": return None
    # Returns (CapitalCity, Country) -> e.g., ("London", "United Kingdom")
    return (cols[1].strip(), cols[0].strip())
country_rdd = sc.textFile("country-list(1).csv") \
                .map(parse_country_list) \
                .filter(lambda x: x is not None)
# Map temp_data to (City, (Year, Temp)) to prepare for the join
# index 2 is City, index 3 is Year, index 4 is Temp
temp_to_join = temp_data.map(lambda x: (x[2].strip(), (x[3].strip(), x[4])))
# Join the datasets on City Name
# Result format: (City, ((Year, Temp), Country))
joined_data = temp_to_join.join(country_rdd)
# Group by (Country, Year) and calculate Average
# We use x[1][1] for Country and x[1][0][0] for Year
results_d = joined_data.map(lambda x: ((x[1][1], x[1][0][0]), (x[1][0][1], 1))) \
                       .reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1])) \
                       .mapValues(lambda x: x[0] / x[1]) \
                       .sortByKey() \
                       .map(lambda x: f"{x[0][0]}\t{x[0][1]}\t{x[1]:.2f}")
# Save the output
save_rdd(results_d, "q2_partD_results")
print("\n Part D: Sorted Capital Temp Results")
for row in results_d.take(10):
    print(row)

import csv
import os
from pyspark import SparkContext

sc = SparkContext.getOrCreate()

def save_rdd(rdd, folder_name):
    if os.path.exists(folder_name):
        os.system(f"rm -rf {folder_name}")
    rdd.saveAsTextFile(folder_name)

def parse_temp_csv(line):
    reader = csv.reader([line])
    columns = next(reader)
    if not columns or columns[0] == "Region": return None
    try:
        # Region(0), Country(1), City(3), Year(6), Temp(7)
        return (columns[0].strip(), columns[1].strip(), columns[3].strip(), columns[6].strip(), float(columns[7]))
    except: return None

temp_data = sc.textFile("city_temperature(1).csv") \
              .map(parse_temp_csv) \
              .filter(lambda x: x is not None and x[4] > -90).cache()

# Part A: Min/Max per Region
res_a = temp_data.map(lambda x: (x[0], (x[4], x[4]))) \
                 .reduceByKey(lambda a, b: (min(a[0], b[0]), max(a[1], b[1]))) \
                 .map(lambda x: f"{x[0]}\t{x[1][0]}\t{x[1][1]}")
save_rdd(res_a, "q2_partA_results")

# Part B: Europe Avg
res_b = temp_data.filter(lambda x: x[0] == "Europe") \
                 .map(lambda x: (x[3], (x[4], 1))) \
                 .reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1])) \
                 .mapValues(lambda x: x[0] / x[1]) \
                 .sortByKey() \
                 .map(lambda x: f"{x[0]}\t{x[1]}")
save_rdd(res_b, "q2_partB_results")

# Part C: Top 10 US Cities
# Note: Using "US" as determined earlier
top_10_us_list = temp_data.filter(lambda x: x[1] == "US") \
                          .map(lambda x: (x[2], (x[4], 1))) \
                          .reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1])) \
                          .mapValues(lambda x: x[0] / x[1]) \
                          .takeOrdered(10, key=lambda x: -x[1])
res_c = sc.parallelize(top_10_us_list).map(lambda x: f"{x[0]}\t{x[1]:.2f}")
save_rdd(res_c, "q2_partC_results")

# Part D: Capitals
def parse_country_list(line):
    reader = csv.reader([line])
    cols = next(reader)
    if not cols or cols[0] == "country": return None
    return (cols[1].strip(), cols[0].strip())

country_rdd = sc.textFile("country-list(1).csv").map(parse_country_list).filter(lambda x: x is not None)
temp_to_join = temp_data.map(lambda x: (x[2], (x[3], x[4])))
joined = temp_to_join.join(country_rdd)

res_d = joined.map(lambda x: ((x[1][1], x[1][0][0]), (x[1][0][1], 1))) \
              .reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1])) \
              .mapValues(lambda x: x[0] / x[1]) \
              .map(lambda x: f"{x[0][0]}\t{x[0][1]}\t{x[1]:.2f}")
save_rdd(res_d, "q2_partD_results")

print("Question 2 outputs saved successfully.")

!zip -r Q2_Results.zip q2_partA_results q2_partB_results q2_partC_results q2_partD_results
